package curs.practic.Util.event;

public enum EntityChangeEventType {
    ADD,
    DELETE,
    ADD_MESSSAGE,
    ADD_USER,
    REMOVE_USER,
    UPDATE_USER,
    SEND_FRIEND_REQUEST,
    ACCEPT_FRIEND_REQUEST,
    REJECT_FRIEND_REQUEST,
    ADD_FRIENDSHIP,
    REMOVE_FRIENDSHIP,
    EXECUTE_EVENT,
    SUBSCRIBE_USER,
    UNSUBSCRIBE_USER,
    PARTICIPATE_USER,
    DROP_OUT_USER,
    CREATE_EVENT,
    DELETE_EVENT
}
